# Generated by Django 6.0.2 on 2026-04-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.CharField(default='', max_length=254, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.CharField(default='', max_length=50, verbose_name='published_date'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='title'),
        ),
    ]
